### ISSUE TITLE
Neovim hangs on Windows

### ISSUE THREAD

**Issue by akiyosi** [tjdevries/express_line.nvim#1]
Inexplicably, adding this plugin seems to cause Nvim to hang when opening a python file with nvim-qt. I haven't been able to fully investigate whether this happens with other file types.

### nvim version

:version
NVIM v0.5.0-624-g1869f86e3

### Steps to reproduce

1. Add the following

``` init.vim
Plug 'tjdevries/luvjob.nvim'
Plug 'tjdevries/express_line.nvim'
```

2. Set file type associations: open `.py` file with nvim-qt.exe 
3. Open `foobar.py` file

### Actual behaviour

nvm-qt hangs.

### Expected behaviour

Can open a file with a `.py` extension

**Comment by tjdevries** [comment]
Hey, thanks for the bug report -- It's most likely that I have some issue on windows and it causes the status line to die. I'll take a look soon to fix this.

I might change the requirements to use `plenary.nvim` instead of `luvjob`, just as a heads up, since I'm thinking of incorporating `luvjob` there into my `stdlib` of neovim stuff. I'll update the readme accordingly when that happens (just install a different plugin basically).

**Comment by tjdevries** [comment]
Hey @akiyosi does this still hang on windows? (It's ok if you haven't checked / stopped using. Just interested)

**Comment by akiyosi** [comment]
Hi
I enabled the plugin again on my company's Windows machine and found that it did not cause any problems. 
Thank you :D

**Comment by tjdevries** [comment]
Awesome, very happy to hear it :) Let me know if you have any other questions!!
